@HotelListing_Host = http://localhost:5049

GET {{HotelListing_Host}}/api/hotels
Accept: application/json

POST {{HotelListing_Host}}/api/hotels/
Content-Type: application/json
{
    "id": 1,
    "name": "Grand Plaza",
    "address": "123 main st."
    "rating": 4.5
}



PUT {{HotelListing_Host}}/api/hotels/1
Content-Type: application/json
{
    "id": 1,
    "name": "Grand Plaza",
    "address": "123 main st."
    "rating": 4.5
}


###
GET {{HotelListing_Host}}/api/Countries

POST {{HotelListing_Host}}/api/Countries
Content-Type: application/json
{
    "id": 1,
    "name": "United States"
}
###
@id=1
GET {{HotelListing_Host}}/api/Countries/{{id}}

###
DELETE {{HotelListing_Host}}/api/Countries/{{id}}

###
GET http://localhost:5049/api/Hotels

###
POST http://localhost:5049/api/Hotels
Content-Type: application/json
{
    "id": 1,
    "name": "Grand Plaza",
    "address": "123 main st.",
    "rating": 4.5
}